config/routes.rb
Rails.application.routes.draw do

  # creats login for sessions, get for new, post for create (create in the controller, starting the session), and /logout for destroy (logging out)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # creates all the urls for the header or anywhere that needs it 
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'
  get '/search', to: 'search#index'
  get '/upload', to: 'quotes#new'
  get '/signup', to: 'users#new'
  get '/quotes', to: 'quotes#index'

  # sets the home/index view to the root url of the website.
  root 'home#index'

  # the models urls, default GET POST DELETE stuff.
  resources :categories
  resources :quotes
  resources :philosophers
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login, except: [:index]

  def index
    # Creating a variable @quote that contains all the details that we will be referencing on the index page referencing quotes, including their categories and the author. Only taking 5 (of the most recently created.)
    @quotes = Quote.joins(:philosopher, :quote_categories, :categories).distinct.take(5)
  end

  def uquotes
        # Creating a variable @quote that contains all the details that we will be referencing on the your quotes page, only merging quotes that contain the current user's user_id, as only their quotes will be shown.
    @quotes = Quote.joins(:philosopher, :quote_categories, :categories).distinct.merge(Quote.where(user_id: current_user.id))
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aindex.html.erb
<!-- This page is the adminstrator landing page, or admin home. Here we simply display some stats of the database, along side buttons that lead to each table where we can modify or enter values. -->
<!-- At the top here we display any notice that was set on the prior view, likely the login successful notice. -->
<p style="color: green"><%= notice %></p>
<h3>Administrator Landing Page</h3>
<hr/>

<div class="form-group" style="padding-bottom: 10px;">
    <h4>Website Statistics:</h4>
    <p>
        <!-- The amount of registered users, link to manage all users. -->
        Registered Users: <%= User.count %> | <%= link_to "Manage Users", users_path %><br>

        <!-- The amount of quotes, link to manage all quotes. -->
        Quotes: <%= Quote.count %> | <%= link_to "Manage Quotes", quotes_path %><br>

        <!-- The amount of philosophers, link to manage all philosophers. -->
        Authors: <%= Philosopher.count %> | <%= link_to "Manage Authors", philosophers_path %><br>

        <!-- The amount of categories, link to manage all categories. -->
        Categories: <%= Category.count %> | <%= link_to "Manage Categories", categories_path %><br>
    </p>
    
</div>

app/views/home/index.html.erb
<!-- This is the home page, or the root_path. This is the first page that you're brought to when entering in the URL of the website. Here we display the 5 most recent quotes, as well as a welcome -->
<h1>Welcome to myQuote</h1>
<hr />
<h3>Recently Added Quotes</h3>

<!-- Renders the 5 most recent text we gathered in the quotes_controller.rb and displays them with the _quote partial in views/quotes/ -->
<%= render partial: 'quotes/quote' %>

app/views/home/uindex.html.erb
<!-- This page is the user landing page, or the userhome page. Here we just show the details of the user, as well as an option to edit account details at the bottom -->
<p style="color: green"><%= notice %></p>
<h1>Account Details</h1>
<hr />
<p>
  <!-- Displays user's full name -->
  <div class="mb-3">
    <label class="form-label"><strong>Name:</strong></label>
    <div><%= current_user.full_name %></div>
  </div>

  <!-- Displays user's email address -->
  <div class="mb-3">
    <label class="form-label"><strong>Email:</strong></label>
    <div><%= current_user.email %></div>
  </div>

  <!-- Displays a placeholder for the password, as the password is encrypted and we cannot access it for security reasons. -->
  <div class="mb-3">
    <label class="form-label"><strong>Current Password:</strong></label>
    <span class="text-danger">ENCRYPTED</span>
  </div>

  <!-- Displays user's account type, this is just a nicer way of saying if the user is an adminstrator or not by viewing the is_admin entry in the user.db -->
  <div class="mb-3">
    <label class="form-label"><strong>Account Type:</strong></label>
    <div>
      <!-- Checks if the current user is an admin -->
      <% if current_user.is_admin %>
        <span>Administrator</span>
      <% else %>
        <span>Standard User</span>
      <% end %>
    </div>
  </div>

  <!-- Displays user's current status; active, suspended -->
  <div class="mb-3">
    <label class="form-label"><strong>Status:</strong></label>
    <div><%= current_user.status %></div>
  </div>
</p>

<%= link_to "Edit your account details", edit_user_path(session[:user_id]) %>

app/views/home/uquotes.html.erb
<!-- 
    This page contains all the user's quotes. 
    Here we grab our quotes that we defined in the home_controller in def uquotes. 
    We then display it using the same partial we used in the home page.
-->
<h3>Your Quotes</h3>
<hr />

<!-- Checks if the user has any quotes. -->
<% if @quotes.present? %>
  <!-- Renders with the _quote partial in views/quotes/ -->
  <%= render partial: 'quotes/quote' %>
<% else %>
<div>
  <!-- Displays fail message if user doesn't have any quotes, and gives an option to upload some. -->
  You have no quotes.
  <%= link_to "Upload", upload_path %>
</div>

<% end %>