config/routes.rb
Rails.application.routes.draw do

  # creats login for sessions, get for new, post for create (create in the controller, starting the session), and /logout for destroy (logging out)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # creates all the urls for the header or anywhere that needs it 
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'
  get '/search', to: 'search#index'
  get '/upload', to: 'quotes#new'
  get '/signup', to: 'users#new'
  get '/quotes', to: 'quotes#index'

  # sets the home/index view to the root url of the website.
  root 'home#index'

  # the models urls, default GET POST DELETE stuff.
  resources :categories
  resources :quotes
  resources :philosophers
  resources :users
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
    # Philosophers can have many quotes, when the philosopher is destroyed, the quotes are destroyed along side.
    has_many :quote, dependent: :destroy

    # Defining full_name so i can reference later, just the first and last name of the philosopher.
    def full_name
        "#{fname} #{lname}"
    end
end

app/controllers/philosophers_controller.rb
class PhilosophersController < ApplicationController
  before_action :set_philosopher, only: %i[ show edit update destroy ]
  before_action :require_admin

  # GET /philosophers or /philosophers.json
  def index
    @philosophers = Philosopher.all
  end

  # GET /philosophers/1 or /philosophers/1.json
  def show
  end

  # GET /philosophers/new
  def new
    @philosopher = Philosopher.new
  end

  # GET /philosophers/1/edit
  def edit
  end

  # POST /philosophers or /philosophers.json
  def create
    @philosopher = Philosopher.new(philosopher_params)

    respond_to do |format|
      if @philosopher.save
        format.html { redirect_to philosopher_url(@philosopher), notice: "Philosopher was successfully created." }
        format.json { render :show, status: :created, location: @philosopher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @philosopher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /philosophers/1 or /philosophers/1.json
  def update
    respond_to do |format|
      if @philosopher.update(philosopher_params)
        format.html { redirect_to philosopher_url(@philosopher), notice: "Philosopher was successfully updated." }
        format.json { render :show, status: :ok, location: @philosopher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @philosopher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /philosophers/1 or /philosophers/1.json
  def destroy
    @philosopher.destroy

    respond_to do |format|
      format.html { redirect_to philosophers_url, notice: "Philosopher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_philosopher
      @philosopher = Philosopher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def philosopher_params
      params.require(:philosopher).permit(:fname, :lname, :b_year, :d_year, :biography)
    end
end

app/helpers/philosophers_helper.rb
module PhilosophersHelper
end

app/views/philosophers/_form.html.erb
<!-- A partial that will display a form that is used to both create and update a category.-->
<%= form_with(model: philosopher) do |form| %>
<!-- Check for errors. -->
  <% if philosopher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(philosopher.errors.count, "error") %> prohibited this philosopher from being saved:</h2>

      <ul>
        <% philosopher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Display a form to enter the philosopher's first name.-->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.label "First Name", style: "display: block" %>
    <%= form.text_field :fname, placeholder: 'First Name', class: 'form-control'%>
  </div>

  <!-- Display a form to enter the philosopher's last name.-->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.label "Last Name", style: "display: block" %>
    <%= form.text_field :lname, placeholder: 'Last Name', class: 'form-control' %>
  </div>

  <!-- Display a form to enter the philosopher's birth year.-->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.label "Birth Year", style: "display: block" %>
    <%= form.date_field :b_year, class: 'form-control'  %>
  </div>

  <!-- Display a form to enter the philosopher's death year.-->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.label "Death Year", style: "display: block" %>
    <%= form.date_field :d_year, class: 'form-control'  %>
  </div>

  <!-- Display a form to enter the philosopher's biography.-->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= form.label :Biography, style: "display: block" %>
    <%= form.text_area :biography, placeholder: 'Biography', class: 'form-control' %>
  </div>

  <!-- Checks if philosopher is being created. If it is, display submit. If the philosopher is being updated instead, display update. -->
  <% if @philosopher.new_record? %>
	  <%= form.submit 'Submit', class: 'btn btn-primary' %>
  <% else %>
    <%= form.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/philosophers/_philosopher.html.erb
<!-- A partial that will display the philosophers in the same way. -->

<div id="<%= dom_id philosopher %>">
  <h3>
    <%= philosopher.full_name %>
  </h3>
  <p>
    <strong>Birth year:</strong>
    <%= philosopher.b_year %>
    <strong> D year:</strong>
    <%= philosopher.d_year %>
  </p>

  <p>
    <strong>Biography:</strong>
    <%= philosopher.biography %>
  </p>
</div>

app/views/philosophers/edit.html.erb
<!-- This view is displayed when editing a philosopher. -->
<h1>Update Philosopher</h1>
<hr />


<!-- Renders the form in views/philosophers/_form with the current philosopher selected. -->
<%= render "form", philosopher: @philosopher %>

<br>

<div>
  <%= link_to "Back to philosophers", philosophers_path %>
</div>
<br>
<br>
<%= button_to "Delete this philosopher", @philosopher, method: :delete %>

app/views/philosophers/index.html.erb
<!-- This page displays all the philosophers, this page is only accessible to adminsitrators. -->
<p style="color: green"><%= notice %></p>

<h1>Philosophers</h1>
<!-- Gives option to add philosophers at the top of the page. -->
<%= link_to "Add Philosopher", new_philosopher_path %>
<hr />

<div id="philosophers">
  <!-- For each philosopher, display the philosopher. -->
  <% @philosophers.each do |philosopher| %>
    <!-- Render the philosopher partial in views/philosopher/_philosopher -->
    <%= render philosopher %>
    <p>
      <%= link_to "Edit this philosopher", edit_philosopher_path(philosopher) %>
    </p>
    <br>
  <% end %>
</div>

app/views/philosophers/new.html.erb
<!-- This view is displayed when creating a Philosopher. -->
<h1>Create Philosopher</h1>
<hr />

<!-- Renders the form in views/philosopher/_form with the current philosopher selected. -->
<%= render "form", philosopher: @philosopher %>
<br>

<div>
  <%= link_to "Back to philosophers", philosophers_path %>
</div>

app/views/philosophers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @philosopher %>

<div>
  <%= link_to "Edit this philosopher", edit_philosopher_path(@philosopher) %> |
  <%= link_to "Back to philosophers", philosophers_path %>

  <%= button_to "Destroy this philosopher", @philosopher, method: :delete %>
</div>