config/routes.rb
Rails.application.routes.draw do

  # creats login for sessions, get for new, post for create (create in the controller, starting the session), and /logout for destroy (logging out)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # creates all the urls for the header or anywhere that needs it 
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'
  get '/search', to: 'search#index'
  get '/upload', to: 'quotes#new'
  get '/signup', to: 'users#new'
  get '/quotes', to: 'quotes#index'

  # sets the home/index view to the root url of the website.
  root 'home#index'

  # the models urls, default GET POST DELETE stuff.
  resources :categories
  resources :quotes
  resources :philosophers
  resources :users
end

app/views/layouts/_header.html.erb
<!-- 
  This is another partial that will be displayed at the top of every page. This is the navbar or header. The navbar helps the user navigate the multiple scenes in an easy way. It always appears at the top and gives the current user all functionality that they have access too.
-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">myQuote</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Quotes', quotes_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Search', search_path, class: "nav-link" %>
        </li>

        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
          </li>
        <% end %>

        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to 'Sign In', login_path, class: "nav-link" %>
          </li>
        <% end %>

        <% if logged_in? && !is_administrator? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">User</a>
            <ul class="dropdown-menu">
              <%= link_to "My Account", userhome_path, class: "dropdown-item" %>
              <%= link_to "My Quotes", your_quotes_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Upload Quotes", upload_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Sign Out", logout_path, method: :delete, class:"dropdown-item"%>
            </ul>
          </li>
        <% end %>

        <% if logged_in? && is_administrator? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
            <ul class="dropdown-menu">
              <%= link_to "Admin Home", admin_path, class: "dropdown-item" %>
              <li><%= link_to 'Manage Users', users_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Sign Out", logout_path, method: :delete, class:"dropdown-item"%>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- This is the application view, this is what everything will run inside of. -->
<!DOCTYPE html>
<html>
  <head>
    <title>Myquote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </head>

  <body>
  <!-- We render the header at the start of the page, this is the partial at views/layouts/_header -->
  <%= render partial: 'layouts/header' %>
  <!-- We create a little container that is buffered from the edges of the screen, to ensure a nice layout. Inside this we display whatever is currently being shown. -->
    <div class="container" style="margin-top:20px;">
      <%= yield %>
    </div>
  </body>
</html>